### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by RohitRathore1** [saezlab/PHONEMeS-ILP#8]
@enio23 
1. https://github.com/saezlab/PHONEMeS-ILP#:~:text=We%20start%20first,provided%20here.
Here script of how the inputs for this case-study have been provided is missing. So if you can provide it then it would be very helpful to know how did you prepare the data.

2. How did you choose the conditions?

**Comment by enio23** [comment]
@RohitRathore1 

1. I am not a maintainer of the package for some time and apparently, the main PHONEMeS repo (https://github.com/saezlab/PHONEMeS/) has changed since I have delegated the maintainer roles. That is why the link is broken and you cannot find the main examples there anymore. However, you can also get the scripts to generate the inputs in the MainData in the Examples [here](https://github.com/enio23/PHONEMeS). Those are quite old scripts though, I did not generate those inputs and I think the scripts will not be well-documented. However, you can have a look there. For better-documented scripts on how the phonemes inputs can be generated, you can refer to the other two examples.

2. The conditions were chosen based on what was reported in the original phonemes manuscript: https://www.nature.com/articles/ncomms9033

**Comment by smuellerd** [comment]
Hi @RohitRathore1! 

We were working on an updated version of PHONEMeS which is more intuitive to use that's why some of the scripts have changed. As @enio23 already mentioned you can still find all the old scripts in PHONEMeS v1.0.0 (https://github.com/saezlab/PHONEMeS/releases/tag/v1.0.0). We also fixed the link now.

The most recent version of PHONEMeS that @enio23 also pointed out is also ILP based and provides a tutorial with a small example (https://github.com/saezlab/PHONEMeS/blob/master/vignettes/tutorial.md). In that version, you can also include protein-protein interactions or stick to the kinase-substrate network. Maybe this would be helpful for you!

**Comment by gabora** [comment]
updated links in the latest commit:  [1117662](https://github.com/saezlab/PHONEMeS-ILP/commit/1117662a0128454a66e250100c613e6caf34dd69)
